(() => {
'use strict';
const $ = s => document.querySelector(s);
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nodes = new Map(), figures = new Map(window.THESIS_FIGURES.map(f => [f.id,f]));
function index(node,parent=null){node.parent=parent;nodes.set(node.id,node);(node.children||[]).forEach(child=>index(child,node));}
index(window.THESIS);
let current = window.THESIS, layout = 'explore';
const breadcrumb = node => {const list=[];for(let n=node;n;n=n.parent)list.unshift(n);return list;};
const descendants = node => [node,...(node.children||[]).flatMap(descendants)];
function navigate(id, view=layout){const safe=nodes.has(id)?id:'home';const hash=`#${safe}${view==='explore'?'':`/${view}`}`;if(location.hash===hash)render();else location.hash=hash;}
function readLocation(){const [id,view]=location.hash.slice(1).split('/');current=nodes.get(id)||window.THESIS;layout=['outline','figures'].includes(view)?view:'explore';render();}
let sourcePage=1;
function updatePage(page){sourcePage=Math.max(1,Math.min(201,Math.round(Number(page)||1)));$('#pdf-title').textContent=`Sijan Regmi · Page ${sourcePage}`;$('#source-page').src=`assets/pages/page-${String(sourcePage).padStart(3,'0')}.jpg`;$('#source-page').alt=`Original dissertation, page ${sourcePage}`;$('#page-number').value=sourcePage;$('#pdf-tab').href=`assets/thesis.pdf#page=${sourcePage}`;$('#prev-page').disabled=sourcePage===1;$('#next-page').disabled=sourcePage===201;$('.reader-stage').scrollTop=0;}
function source(page){updatePage(page);if(!$('#pdf-dialog').open)$('#pdf-dialog').showModal();}
$('#prev-page').onclick=()=>updatePage(sourcePage-1);$('#next-page').onclick=()=>updatePage(sourcePage+1);$('#page-number').onchange=e=>updatePage(e.target.value);
$('.skip').onclick=e=>{e.preventDefault();$('#content').focus();};
$('#figure-zoom').onclick=()=>{const zoomed=$('.image-stage').classList.toggle('zoomed');$('#figure-zoom').textContent=zoomed?'Fit figure':'Zoom in';};
function showFigure(id){const f=figures.get(id);if(!f)return;$('.image-stage').classList.remove('zoomed');$('#figure-zoom').textContent='Zoom in';$('#figure-number').textContent=`FIGURE ${f.number} · THESIS PAGE ${f.page}`;$('#figure-title').textContent=f.title;$('#figure-image').src=f.src;$('#figure-image').alt=`Figure ${f.number}: ${f.title}. ${f.caption}`;$('#figure-caption').textContent=f.caption;$('#figure-source').onclick=()=>source(f.page);$('#figure-dialog').showModal();}
function figureCard(id){const f=figures.get(id);return `<button class="figure-preview" data-figure="${f.id}" aria-label="Enlarge Figure ${f.number}: ${escape(f.title)}"><img src="${f.src}" alt="${escape(f.title)}" loading="lazy"><div class="figure-info"><small>FIGURE ${f.number} · PAGE ${f.page}</small><h3>${escape(f.title)}</h3><p>${escape(f.caption)}</p><span class="expand">Enlarge figure ↗</span></div></button>`;}
function card(n,i){const depth=n.children?.length||0;return `<button class="card ${n.id==='analysis'?'featured':n.id==='results'?'result-card core':n.id==='calibration'?'core':''}" data-node="${n.id}"><div class="card-top"><span class="card-num">${escape(n.num||String(i+1).padStart(2,'0'))}</span>${n.tag?`<span class="tag">${escape(n.tag)}</span>`:depth?`<span class="tag">${depth} TOPICS</span>`:''}</div><h3>${escape(n.title)}</h3><p>${escape(n.summary||'')}</p><div class="card-bottom"><span>${depth?'Explore topics':n.figure?'View key ideas & figure':'View key ideas'} · p. ${n.page}</span><span class="arrow" aria-hidden="true">↗</span></div></button>`;}
function related(node){return node.related?.length?`<div class="related"><small>CONNECTED TOPICS</small><div>${node.related.map(id=>`<button data-node="${id}">${escape(nodes.get(id).title)} →</button>`).join('')}</div></div>`:'';}
function explore(node){let html='';if(node.takeaway)html+=`<div class="takeaway"><span class="spark" aria-hidden="true">✳</span><div><small>THE KEY IDEA</small><p>${escape(node.takeaway)}</p></div></div>`;
if(node.id!=='home' && (node.phrases?.length||node.figure))html+=`<div class="detail-grid ${node.figure?'':'no-figure'}">${node.phrases?.length?`<div class="core-panel"><h2>Core ideas</h2><ul class="phrase-list">${node.phrases.map((p,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span>${escape(p)}</li>`).join('')}</ul></div>`:''}${node.figure?figureCard(node.figure):''}</div>`;
if(node.children?.length){html+=`<div class="section-label"><span>${node.id==='home'?'The structure of your thesis':'Choose the next layer'}</span><span>${node.children.length} ${node.id==='home'?'chapters & collections':'topics'} · click to explore</span></div><div class="cards">${node.children.map(card).join('')}</div>`;}
if(node.id==='home')html+=`<div class="reading-path"><span class="icon" aria-hidden="true">↳</span><div><strong>Follow the measurement</strong><p>Calibration → event selection → signal extraction → results</p></div><button data-node="calibration">Start with calibration →</button></div>`;
if(!node.children?.length)html+=`<div class="reading-path"><span class="icon" aria-hidden="true">¶</span><div><strong>Keep the full context close</strong><p>Read the original text and figure captions in your dissertation.</p></div><button data-page="${node.page}">Open page ${node.page} ↗</button></div>`;
return html+related(node);}
function outlineNode(n,level=0){if(n.children?.length)return `<details ${level===0?'open':''}><summary><span>${escape(n.num?n.num+' · ':'')}${escape(n.title)}</span><small>${n.children.length} topics · p. ${n.page}</small></summary><div class="branch"><div class="leaf"><button data-node="${n.id}" data-layout="explore">Open this overview ↗</button></div>${n.children.map(c=>outlineNode(c,level+1)).join('')}</div></details>`;return `<div class="leaf"><button data-node="${n.id}" data-layout="explore">${escape(n.title)} ↗</button><small>p. ${n.page}</small></div>`;}
function outline(node){return `<div class="outline-tools"><button data-outline="open">Expand all</button><button data-outline="close">Collapse all</button></div><div class="outline-tree">${(node.children||[node]).map(n=>outlineNode(n)).join('')}</div>`;}
function gallery(node){const ids=[...new Set(descendants(node).filter(n=>n.figure).map(n=>n.figure))];return ids.length?`<div class="section-label"><span>Selected original figures</span><span>${ids.length} representative ${ids.length===1?'figure':'figures'}</span></div><div class="gallery">${ids.map(figureCard).join('')}</div>`:`<div class="empty"><h2>A concise text overview</h2><p>This topic has no selected figure. Read the core ideas or browse the full figure collection.</p><button class="primary" data-node="home" data-layout="figures">Browse all figures</button></div>`;}
function render(){const path=breadcrumb(current),chapter=path[1];document.title=`${current.label||current.title} · Thesis Atlas`;$('#chapters').innerHTML=[window.THESIS,...window.THESIS.children].map(n=>`<a href="#${n.id}" class="${n===(chapter||current)?'active':''}" ${n===(chapter||current)?'aria-current="page"':''}><span>${n.num||'⌂'}</span><span>${escape(n.label)}</span></a>`).join('');$('#breadcrumbs').innerHTML=path.map((n,i)=>`${i?'<span aria-hidden="true">/</span>':''}${i===path.length-1?`<span class="current">${escape(n.label||n.title)}</span>`:`<button data-node="${n.id}">${escape(n.label||n.title)}</button>`}`).join('');$('#up').hidden=!current.parent;$('#up').onclick=()=>navigate(current.parent.id);const home=current.id==='home';$('#heading').innerHTML=`<div class="${home?'home-hero':''}"><div class="intro-head"><div class="eyebrow">${home?'An interactive dissertation':current.tag||`${chapter?.num||''} · ${chapter?.label||'Thesis'} / Layer ${path.length-1}`}</div><h1>${escape(current.title)}</h1><p>${escape(current.summary||'')}</p>${home?`<div class="chips">${current.phrases.map(p=>`<span class="chip">${escape(p)}</span>`).join('')}</div>`:`<div class="heading-actions"><button class="source-link" data-page="${current.page}">Read in thesis · page ${current.page} ↗</button><span class="chip">${current.children?.length?current.children.length+' paths to explore':'Topic detail'}</span></div>`}</div>${home?'<div class="orbit" aria-hidden="true"><div class="ring"></div><div class="ring r2"></div><div class="ring r3"></div><span class="nucleus">π⁰ η</span><span class="particle p1"></span><span class="particle p2"></span><span class="orbit-label">TWO PHOTONS. ONE STORY.</span></div>':''}</div>`;
 document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===layout));$('#view-hint').textContent={explore:'One idea at a time. Go as deep as you like.',outline:'Expand branches to see the whole structure.',figures:'Repeated plots condensed to one example.'}[layout];$('#view').innerHTML=({explore,outline,figures:gallery}[layout])(current);$('#search-results').hidden=true;window.scrollTo({top:0,behavior:'instant'});}
document.addEventListener('click',e=>{const b=e.target.closest('[data-node],[data-page],[data-figure],[data-view],[data-close],[data-outline]');if(!b)return;if(b.dataset.node){navigate(b.dataset.node,b.dataset.layout||layout);$('#search').value='';}else if(b.dataset.page)source(Number(b.dataset.page));else if(b.dataset.figure)showFigure(b.dataset.figure);else if(b.dataset.view)navigate(current.id,b.dataset.view);else if(b.dataset.close)$('#'+b.dataset.close).close();else if(b.dataset.outline)document.querySelectorAll('.outline-tree details').forEach(d=>d.open=b.dataset.outline==='open');});
$('#full-pdf').onclick=()=>source(1);
function search(){const q=$('#search').value.trim().toLowerCase(),box=$('#search-results');if(!q){box.hidden=true;return;}const matches=[...nodes.values()].filter(n=>n.id!=='home' && `${n.title} ${n.summary||''} ${(n.phrases||[]).join(' ')} ${n.figure?figures.get(n.figure).number:''}`.toLowerCase().includes(q)).slice(0,14);box.innerHTML=matches.length?matches.map(n=>`<button data-node="${n.id}" data-layout="explore">${escape(n.title)}<small>${escape(breadcrumb(n).slice(1,-1).map(p=>p.label||p.title).join(' / ')||'Thesis')} · page ${n.page}</small></button>`).join(''):'<p>No matching topics. Try “calibration”, “ratio”, or “XGBoost”.</p>';box.hidden=false;}
$('#search').addEventListener('input',search);$('#search').addEventListener('focus',()=>{if($('#search').value)search();});$('#search').addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();$('#search-results button')?.focus();}if(e.key==='Enter')$('#search-results button')?.click();});
$('#search-results').addEventListener('keydown',e=>{const list=[...document.querySelectorAll('#search-results button')],i=list.indexOf(document.activeElement);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();list[(i+(e.key==='ArrowDown'?1:-1)+list.length)%list.length]?.focus();}});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();$('#search').focus();}if(e.key==='Escape')$('#search-results').hidden=true;});document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))$('#search-results').hidden=true;});
for(const d of document.querySelectorAll('dialog'))d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});
window.addEventListener('hashchange',readLocation);readLocation();
})();
